config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
    root "pages#home"
    get '/about', to: 'pages#about'
    get '/help' , to: 'pages#help'

    resources :todos
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/todo.rb
class Todo <ApplicationRecord
    validates :name, presence: true 
    validates :description, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    def hello
        render plain:"Hello World"
    end
    
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

    def home

    end
    def about

    end
    def help
        
    end
end

app/controllers/todos_controller.rb
class TodosController<ApplicationController

    before_action :set_todo, only: [:edit,:show,:update,:destroy]

    def new
        @todo = Todo.new
    end

    def create
        @todo = Todo.new(todo_params)
        if @todo.save
            flash[:notice] = "Todo created successfully"
            redirect_to todo_path(@todo)
        else
            render 'new', status: :unprocessable_entity
        end
    end

    def show 
        
    end

    def edit
        
    end

    def update
        
        if @todo.update(todo_params)
            flash[:notice] = "Todo Updated Successfully"
            redirect_to todo_path(@todo)
        else
            render 'edit', status: :unprocessable_entity
        end
    end

    def index
        @todos = Todo.all
    end

    def destroy

        @todo.destroy
        flash[:notice] = "Todo Deleted Successfully"
        redirect_to todo_path
    end

    private 
        
        def set_todo
            @todo =Todo.find(params[:id])
        end
        def todo_params
            params.require(:todo).permit(:name,:description)
        end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_messages.html.erb
<% flash.each do |ans,msg| %>
      <ul>
        <li>
          <%= msg %>
        </li>
      </ul>
    <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ToDoApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'layouts/messages' %>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>About Page</h1>

app/views/pages/help.html.erb
<h1>Help Page</h1>

app/views/pages/home.html.erb
<h1>Hello World</h1>

app/views/todos/_form.html.erb
<% if @todo.errors.any? %>
    <h2>Here are the following errors which prevent it from performing current action </h2>
    <ul>
        <% @todo.errors.full_messages.each do |msg| %>
            <li>
                <%= msg%>
            </li>
        <% end %>
    </ul>
<% end %>

<%= form_for @todo do |e| %>
    <p>
        <%= e.label :name%><br>
        <%= e.text_field :name%>
    </p>
    <p>
        <%= e.label :Description %><br>
        <%= e.text_area :description %>
    </p>
    <p>
        <%= e.submit %>
    </p>
<% end %>
<%= link_to "Go Back", todos_path %>

app/views/todos/edit.html.erb
<h1>In Edit Form</h1>

<%= render 'form'%>

app/views/todos/index.html.erb
<h1>Index PAge</h1>

<p>
    <%= link_to "Add New Todo", new_todo_path %>
</p>

<table>
    <tr>
        <th>Name</th>
        <th>Description</th>
        <th>Show</th>
        <th>Edit</th>
        <th>Delte</th>
    </tr>
    
    <% @todos.each do |t| %>
    <tr>
        <td><%= t.name %></td>
        <td> <%= t.description %> </td>
        <td> <%= link_to "Show", todo_path(t) %></td>
        <td> <%= link_to "Update", edit_todo_path(t) %></td>
        <td><%= link_to 'delete', todo_path(t), data: {turbo_method: :delete, turbo_confirm: 'Are you sure?' } %></td>
    </tr>
    <% end %>
</table>

app/views/todos/new.html.erb
<h1>Create a new Todo</h1>

<%= render 'form' %>

app/views/todos/show.html.erb
<h1>Here in Show</h1>

<p>
    Name : <%= @todo.name%>
</p>

<p>
    Description: <%= @todo.description %>
</p>

<p>
    <%= link_to "Edit", edit_todo_path(@todo) %> |
    <%= link_to "Go Back", todos_path%>
</p>